"""
系统常量定义
"""

import os

# 交易相关常量
TRADING_DAYS_PER_YEAR = 252
MINUTES_PER_TRADING_DAY = 240  # 4小时交易时间
DEFAULT_TIMEZONE = "Asia/Shanghai"

# 数据相关常量
MAX_SYMBOLS_PER_REQUEST = 100
DEFAULT_LOOKBACK_DAYS = 252
DATA_QUALITY_THRESHOLD = 0.95

# 模型训练常量
DEFAULT_BATCH_SIZE = 32
MAX_EPOCHS = 100
EARLY_STOPPING_PATIENCE = 10

# 风险管理常量
MIN_POSITION_SIZE = 0.01  # 最小仓位比例
MAX_POSITION_PCT = 0.1    # 最大单个仓位比例
DEFAULT_SLIPPAGE_BPS = 5   # 默认滑点（基点）

# 系统常量
LOG_LEVEL = "INFO"
MAX_RETRY_ATTEMPTS = 3
TIMEOUT_SECONDS = 30

# API相关常量
DEFAULT_API_PORT = 8000
DEFAULT_API_HOST = "0.0.0.0"

# 数据库常量
DEFAULT_DB_PATH = os.path.join("data", "finloom.db")
MAX_DB_CONNECTIONS = 10

# 缓存常量
DEFAULT_CACHE_SIZE = 1000
DEFAULT_CACHE_TTL = 3600  # 1小时

# 监控常量
HEALTH_CHECK_INTERVAL = 60  # 秒
METRICS_PORT = 8001

# 文件路径常量
LOG_DIR = "logs"
DATA_DIR = "data"
MODEL_DIR = "models"
CACHE_DIR = "cache"
CONFIG_DIR = "config"

# 消息队列常量
DEFAULT_QUEUE_SIZE = 10000
MESSAGE_TIMEOUT_MS = 5000

# 性能常量
MAX_WORKERS = 4
THREAD_POOL_SIZE = 10
ASYNC_TIMEOUT = 30